data: 
  mode: RS
  transform:
    img:  
      source: [solution, piece, layout]
      img_size: [none, 128, 128]


model:
  unet:
    input_size: [7, 128, 128]
    output_dim: 5
    hidden_dims: [64, 128, 256, 512]
    self_attn: [false, false, true, true]
    cross_attn: false
    shared_attn: false 
    use_coords: true
    num_blocks: [2, 2, 1, 1]
    attention:
      num_head_channels: 64
    bottleneck: true 
    out:
      norm: group
      activation: silu
    residual:
      norm: group
      activation: silu 
    down:
      with_conv: true 
    up:
      with_conv: true
      mode: nearest
  time:
    embed_dim: 128
    output_dim: 256

dm:
  name: flow
  sampler:
    name: beta
    alpha: 1
    beta: 1
  uncertainty:
    weight: 0.01 
    start_on: 0
    patch_size: 8

optimizer:
  name: adamw
  lr: 0.0001
  batch_size: 128
  max_norm: 1.0
  ema: 0.999
  scheduler:
    name: linear
    start_factor: 1e-8
    total_iters: 5e3

train:
  batch_size: 64
  max_steps: 3e5

eval: 
  batch_size: 128

predict:
  batch_size: 128
