data: 
  mode: RS
  transform:
    img: 
      source: [A, B, S]
      img_size: [3, 128, 128]
    slot: 
      source: [A, B, S]
      img_size: [3, 128, 128]

model:
  unet: 
    input_size: [9, 128, 128]
    output_dim: 5
    use_coords: true
    hidden_dims: [64, 128, 256, 512]
    self_attn: [false, false, true, true]
    shared_attn: [false, false, true, true, true]
    num_blocks: [2, 2, 1, 1]
    attention:
      num_head_channels: 64
    bottleneck: true 
    out:
      norm: group
      activation: silu
    residual:
      norm: group
      activation: silu 
    down:
      with_conv: true 
    up:
      with_conv: true
      mode: nearest
  time:
    embed_dim: 128
    output_dim: 256
  slot:
    img_size: [3, 128, 128]
    num_slots: 6
    iters: 3
    hidden_size: [256, 8, 8]
    encoder:
      hidden_dims: [32, 64, 128, 256]
      num_convs: 2
      norm: none
    decoder:
      hidden_dims: [256, 128, 64, 32]
      num_convs: 2
      norm: none
    path: logicface-6.pt # set by default, change if you want to try a different autoencoder
  rel:
    num_layers: 6
    hidden_dim: 128
    pdrop:
      training: [0, 0, 0.5]
      inference: [0, 0, 1]

dm:
  name: flow
  sampler:
    name: beta
    alpha: 1
    beta: 1
  uncertainty:
    weight: 0.01 
    start_on: 0
    patch_size: 8

optimizer:
  name: adamw
  lr: 0.0001
  batch_size: 128
  max_norm: 1.0
  ema: 0.999
  scheduler:
    name: linear
    start_factor: 1e-8
    total_iters: 1e4

train:
  batch_size: 64
  max_steps: 3e5

eval: 
  batch_size: 128

predict:
  batch_size: 128
